name: flutter_project
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  animate_do: ^3.3.4        
  glassmorphism: ^3.0.0 
  marquee: ^2.2.3
  cupertino_icons: ^1.0.8

  # --- Firebase packages ---
  firebase_core: ^3.0.0
  firebase_auth: ^5.0.0
  google_sign_in: ^6.2.4
  cloud_firestore: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/auth/1.png
    - assets/auth/2.png
    - assets/auth/google.png
    - assets/auth/gs.png
    - assets/auth/bangles.jpeg
    - assets/auth/earring.png
    - assets/auth/necklace.png
    - assets/auth/log.png
    - assets/auth/ring.png
    - assets/auth/coin.jpeg
    - assets/auth/emeraldearrings.jpeg
    - assets/auth/luxuryring.jpeg
    - assets/auth/pearlnecklace.jpeg
    - assets/auth/diamondbangles.jpeg
    - assets/auth/ring1.jpeg
    - assets/auth/ring2.jpeg
    - assets/auth/ring3.jpeg
    - assets/auth/ring4.jpeg
    - assets/auth/ring5.jpeg
    - assets/auth/ring6.jpeg
    - assets/auth/nacklace1.jpeg
    - assets/auth/nacklace2.jpeg
    - assets/auth/nacklace3.jpeg
    - assets/auth/nacklace4.jpeg
    - assets/auth/nacklace5.jpeg
    - assets/auth/nacklace6.jpeg
    - assets/auth/su.png

  


  
