// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_Co5bdT9VZ6vrwKQuTb7KTDnsHSXiWLY',
    appId: '1:945540945656:web:df05209dc125ab9d90cd0d',
    messagingSenderId: '945540945656',
    projectId: 'jewellary-marketing-app',
    authDomain: 'jewellary-marketing-app.firebaseapp.com',
    storageBucket: 'jewellary-marketing-app.firebasestorage.app',
    measurementId: 'G-84NP5K4S60',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTo8Ka-80Ck_dTapBjNn7F7MZWQbmMgUg',
    appId: '1:945540945656:android:397364cb818767f090cd0d',
    messagingSenderId: '945540945656',
    projectId: 'jewellary-marketing-app',
    storageBucket: 'jewellary-marketing-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtYywc4W_L9y01BtWYGVKQgFQ1NysEhcs',
    appId: '1:945540945656:ios:6a4b411a4ee1a61b90cd0d',
    messagingSenderId: '945540945656',
    projectId: 'jewellary-marketing-app',
    storageBucket: 'jewellary-marketing-app.firebasestorage.app',
    androidClientId: '945540945656-r8qoib7hvbilc9n8nar13u2tf04hivav.apps.googleusercontent.com',
    iosClientId: '945540945656-rh6rtu34b5fr439c10dki72cs26mafll.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtYywc4W_L9y01BtWYGVKQgFQ1NysEhcs',
    appId: '1:945540945656:ios:6a4b411a4ee1a61b90cd0d',
    messagingSenderId: '945540945656',
    projectId: 'jewellary-marketing-app',
    storageBucket: 'jewellary-marketing-app.firebasestorage.app',
    androidClientId: '945540945656-r8qoib7hvbilc9n8nar13u2tf04hivav.apps.googleusercontent.com',
    iosClientId: '945540945656-rh6rtu34b5fr439c10dki72cs26mafll.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_Co5bdT9VZ6vrwKQuTb7KTDnsHSXiWLY',
    appId: '1:945540945656:web:8357f58fdaf7aa8090cd0d',
    messagingSenderId: '945540945656',
    projectId: 'jewellary-marketing-app',
    authDomain: 'jewellary-marketing-app.firebaseapp.com',
    storageBucket: 'jewellary-marketing-app.firebasestorage.app',
    measurementId: 'G-FM9MDPCKV0',
  );

}