// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABP5FPdi2tjVSqpHH5qt_C4Uv4uGQvP60',
    appId: '1:182392336907:web:5335adf741addc80dbcd0e',
    messagingSenderId: '182392336907',
    projectId: 'jewelleryapp-60723',
    authDomain: 'jewelleryapp-60723.firebaseapp.com',
    storageBucket: 'jewelleryapp-60723.firebasestorage.app',
    measurementId: 'G-ECSDJJ0E9V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCViMpdp7o6HExvwBdNH07vHrGUy21L5Mo',
    appId: '1:182392336907:android:5aa6cbf3e8b4c343dbcd0e',
    messagingSenderId: '182392336907',
    projectId: 'jewelleryapp-60723',
    storageBucket: 'jewelleryapp-60723.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnjRIWKhHUNeATK-W4clqHnDPDfgL-BBo',
    appId: '1:182392336907:ios:aa5b4629952afc08dbcd0e',
    messagingSenderId: '182392336907',
    projectId: 'jewelleryapp-60723',
    storageBucket: 'jewelleryapp-60723.firebasestorage.app',
    iosClientId: '182392336907-7j9ttfv4gn6umsacjfgc0a4cr552arsc.apps.googleusercontent.com',
    iosBundleId: 'com.example.jewelleryAdminApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnjRIWKhHUNeATK-W4clqHnDPDfgL-BBo',
    appId: '1:182392336907:ios:aa5b4629952afc08dbcd0e',
    messagingSenderId: '182392336907',
    projectId: 'jewelleryapp-60723',
    storageBucket: 'jewelleryapp-60723.firebasestorage.app',
    iosClientId: '182392336907-7j9ttfv4gn6umsacjfgc0a4cr552arsc.apps.googleusercontent.com',
    iosBundleId: 'com.example.jewelleryAdminApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyABP5FPdi2tjVSqpHH5qt_C4Uv4uGQvP60',
    appId: '1:182392336907:web:cd1360eca8a17eb8dbcd0e',
    messagingSenderId: '182392336907',
    projectId: 'jewelleryapp-60723',
    authDomain: 'jewelleryapp-60723.firebaseapp.com',
    storageBucket: 'jewelleryapp-60723.firebasestorage.app',
    measurementId: 'G-GXC7VSYMSG',
  );
}
